Repository akulackovan/PhotoBank, pull requests merged in 2023-01, with the labels that each got.

#3 Шапка сайта front
  server/client/src/App.js
  server/client/src/App.scss
  server/client/src/components/NavBar/NavBar.jsx
  server/client/src/components/NavBar/NavBar.scss
  server/client/src/index.js
  server/client/src/index.scss
Labels: front

#5 Логин front
  server/client/src/App.js
  server/client/src/App.scss
  server/client/src/context/AuthContext.js
  server/client/src/hooks/auth.hook.js
  server/client/src/index.js
  server/client/src/index.scss
  server/client/src/pages/AuthPage/AuthPage.jsx
  server/client/src/pages/AuthPage/AuthPage.scss
  server/client/src/routes.js
  server/index.js
Labels: front

#8 Настройки пользователя backend
  server/controllers/settings.js
  server/index.js
  server/router/settings.js
Labels: backend

#6 Настройки пользователя front
  server/client/src/pages/SettingsPage/SettingPage.jsx
  server/client/src/pages/SettingsPage/SettingsPage.scss
Labels: front

#4 Регистрация front
  server/client/App.js
  server/client/App.scss
  server/client/index.js
  server/client/index.scss
  server/client/src/pages/RegPage/RegPage.jsx
  server/client/src/pages/RegPage/RegPage.scss
Labels: front

#2 Получение постов пользователя backend
  server/controllers/getPostById.js
  server/controllers/getPostByUserId.js
  server/index.js
  server/models/Post.js
Labels: backend

#7 Регистрация и авторизация пользователя backend
  server/controllers/auth.js
  server/index.js
  server/models/City.js
  server/models/Comment.js
  server/models/Post.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/router/auth.js
  server/router/posts.js
  server/utils/checkAuth.js
Labels: backend

#1 Получение постов подписчиков, популярных постов, создание и удаление поста backend
  server/controllers/auth.js
  server/controllers/getPopularPosts.js
  server/controllers/getSubscriptionPosts.js
  server/controllers/postController.js
  server/router/auth.js
Labels: backend

#9 Создание поста front
  server/client/src/components/CityCombobox/CityCombobox.jsx
  server/client/src/components/CityCombobox/CityCombobox.scss
  server/client/src/components/Cropper/cropper.jsx
  server/client/src/components/Cropper/cropper.scss
  server/client/src/pages/AddPostPage/AddPostPage.jsx
  server/client/src/pages/AddPostPage/AddPostPage.scss
  server/controllers/getPopularPosts.js
  server/controllers/getSubscriptionPosts.js
  server/controllers/postController.js
Labels: front

#12 Get popular post front
  server/client/App.js
  server/client/App.scss
  server/client/index.js
  server/client/index.scss
  server/client/src/App.js
  server/client/src/App.scss
  server/client/src/components/NavBar/NavBar.jsx
  server/client/src/components/NavBar/NavBar.scss
  server/client/src/context/AuthContext.js
  server/client/src/hooks/auth.hook.js
  server/client/src/index.js
  server/client/src/index.scss
  server/client/src/pages/AuthPage/AuthPage.jsx
  server/client/src/pages/AuthPage/AuthPage.scss
  server/client/src/pages/PopularPage/PopularPage.jsx
  server/client/src/pages/PopularPage/PopularPage.scss
  server/client/src/pages/RegPage/RegPage.jsx
  server/client/src/pages/RegPage/RegPage.scss
  server/client/src/pages/SettingsPage/SettingPage.jsx
  server/client/src/pages/SettingsPage/SettingsPage.scss
  server/client/src/routes.js
  server/controllers/auth.js
  server/controllers/getPopularPosts.js
  server/controllers/getPostById.js
  server/controllers/getPostByUserId.js
  server/controllers/getSubscriptionPosts.js
  server/controllers/postController.js
  server/controllers/settings.js
  server/index.js
  server/models/City.js
  server/models/Comment.js
  server/models/Post.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/router/auth.js
  server/router/posts.js
  server/router/settings.js
  server/utils/checkAuth.js
Labels: front

#16 Hot fix get popular post
  server/client/App.js
  server/client/App.scss
  server/client/index.js
  server/client/index.scss
  server/client/src/App.js
  server/client/src/App.scss
  server/client/src/components/NavBar/NavBar.jsx
  server/client/src/components/NavBar/NavBar.scss
  server/client/src/context/AuthContext.js
  server/client/src/hooks/auth.hook.js
  server/client/src/index.js
  server/client/src/index.scss
  server/client/src/pages/AuthPage/AuthPage.jsx
  server/client/src/pages/AuthPage/AuthPage.scss
  server/client/src/pages/PopularPage/PopularPage.jsx
  server/client/src/pages/PopularPage/PopularPage.scss
  server/client/src/pages/RegPage/RegPage.jsx
  server/client/src/pages/RegPage/RegPage.scss
  server/client/src/pages/SettingsPage/SettingPage.jsx
  server/client/src/pages/SettingsPage/SettingsPage.scss
  server/client/src/routes.js
  server/controllers/auth.js
  server/controllers/getPopularPosts.js
  server/controllers/getPostById.js
  server/controllers/getPostByUserId.js
  server/controllers/getSubscriptionPosts.js
  server/controllers/postController.js
  server/controllers/settings.js
  server/index.js
  server/models/City.js
  server/models/Comment.js
  server/models/Post.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/router/auth.js
  server/router/posts.js
  server/router/settings.js
  server/utils/checkAuth.js
Labels: front, backend

#18 Get popular post front
  server/client/src/pages/PopularPage/PopularPage.jsx
  server/client/src/pages/PopularPage/PopularPage.scss
  server/controllers/getPopularPosts.js
Labels: front, backend

#10 Dev settings
  server/client/App.js
  server/client/App.scss
  server/client/index.js
  server/client/index.scss
  server/client/package-lock.json
  server/client/package.json
  server/client/src/App.scss
  server/client/src/hooks/use.theme.js
  server/client/src/index.scss
  server/client/src/pages/RegPage/RegPage.jsx
  server/client/src/pages/RegPage/RegPage.scss
  server/client/src/pages/SettingsPage/SettingPage.jsx
  server/client/src/pages/SettingsPage/SettingsPage.scss
  server/controllers/city.js
  server/controllers/settings.js
  server/index.js
Labels: front, backend

#13 Dev another user front
  server/client/package-lock.json
  server/client/package.json
  server/client/src/App.js
  server/client/src/App.scss
  server/client/src/components/AnotherPage/AnotherPage.jsx
  server/client/src/components/AnotherPage/AnotherPage.scss
  server/client/src/components/CityCombobox/CityCombobox.jsx
  server/client/src/components/CityCombobox/CityCombobox.scss
  server/client/src/components/Cropper/cropper.jsx
  server/client/src/components/Cropper/cropper.scss
  server/client/src/components/NavBar/NavBar.jsx
  server/client/src/components/NavBar/NavBar.scss
  server/client/src/context/AuthContext.js
  server/client/src/hooks/auth.hook.js
  server/client/src/hooks/use.theme.js
  server/client/src/index.js
  server/client/src/index.scss
  server/client/src/pages/AddPostPage/AddPostPage.jsx
  server/client/src/pages/AddPostPage/AddPostPage.scss
  server/client/src/pages/AnotherUserPage/AnotherUserPage.jsx
  server/client/src/pages/AuthPage/AuthPage.jsx
  server/client/src/pages/AuthPage/AuthPage.scss
  server/client/src/pages/PopularPage/PopularPage.jsx
  server/client/src/pages/PopularPage/PopularPage.scss
  server/client/src/pages/RegPage/RegPage.jsx
  server/client/src/pages/RegPage/RegPage.scss
  server/client/src/pages/SettingsPage/SettingPage.jsx
  server/client/src/pages/SettingsPage/SettingsPage.scss
  server/client/src/routes.js
  server/controllers/auth.js
  server/controllers/city.js
  server/controllers/getPopularPosts.js
  server/controllers/getPostById.js
  server/controllers/getPostByUserId.js
  server/controllers/getSubscriptionPosts.js
  server/controllers/postController.js
  server/controllers/settings.js
  server/index.js
  server/models/City.js
  server/models/Comment.js
  server/models/Post.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/router/auth.js
  server/router/posts.js
  server/router/settings.js
  server/utils/checkAuth.js
Labels: front

#20 Dev another user front
  server/client/src/components/AnotherPage/AnotherPage.jsx
  server/client/src/components/AnotherPage/AnotherPage.scss
  server/client/src/pages/AnotherUserPage/AnotherUserPage.jsx
Labels: front
